package com.vipin.exception;

public class ChainedExceptionsDemo {

	
	public static void main(String s[]) {
		
		int a = 0;
		
		try {
			if (a==0) {
				throw new ArithmeticException();
			}
		}
		catch (Exceptio)
		
	}
}
